apiVersion: v1
kind: Pod
metadata:
  name: secret-agent
spec:
  serviceAccountName: secret-agent
  containers:
    - name: secret-agent-container
      image: gcr.io/${PROJECT_ID}/secret-agent
      env:
      - name: SECRET_URL
        value: ${SECRET_URL}

